---

- name: enable systemd-networkd
  service: name=systemd-networkd enabled=yes state=started
  when: systemd_conf_network or systemd_conf_link or systemd_conf_netdev

- name: copy .link profiles
  template:
    src: "systemd_conf.j2"
    dest: "/etc/systemd/network/{{ item.key }}.link"
    mode: 0644
  with_dict: "{{ systemd_conf_link }}"
  notify:
    - restart systemd-networkd

- name: copy .netdev profiles
  template:
    src: "systemd_conf.j2"
    dest: "/etc/systemd/network/{{ item.key }}.netdev"
    mode: 0644
  with_dict: "{{ systemd_conf_netdev }}"
  notify:
    - restart systemd-networkd

- name: copy .network profiles
  template:
    src: "systemd_conf.j2"
    dest: "/etc/systemd/network/{{ item.key }}.network"
    mode: 0644
  with_dict: "{{ systemd_conf_network }}"
  notify:
    - restart systemd-networkd

- name: copy .conf profiles
  template:
    src: "systemd_conf.j2"
    dest: "/etc/systemd/{{ item.key }}.conf"
    mode: 0644
  with_dict: "{{ systemd_conf }}"

- name: copy .service profiles
  template:
    src: "systemd_conf.j2"
    dest: "/etc/systemd/system/{{ item.key }}.service"
    mode: 0644
  with_dict: "{{ systemd_conf_service }}"
  notify:
    - daemon-reload

- name: copy .timer profiles
  template:
    src: "systemd_conf.j2"
    dest: "/etc/systemd/system/{{ item.key }}.timer"
    mode: 0644
  with_dict: "{{ systemd_conf_timer }}"
  notify:
    - daemon-reload

# vim: set ts=2 sw=2:
